### ISSUE TITLE
Checklist for release

### ISSUE THREAD

**Issue by gautada** [gautada/gitea-container#14]
### Checklist

- [x] README conforms to the [gist](https://gist.github.com/gautada/ec549c846e8e50daf355d01b06eb0665)
- [x] .gitignore conforms to the [gist](https://gist.github.com/gautada/3a0a4a76d3c7e4539e71fc02c7f599ad)
- [x] Confirm the drone.yml file
- [x] Volume folders are present (development-volume & backup-volume)
- [x] docker-compose(.yml) works
- [x] Manifst folder present (and origin to private repository is correct
- [x] Issue List is linked to proper URI
- [ ] Signoff ({date and signature of last check})
- [ ] Confirm backup (maybe add to testing layer)
- [ ] Confirm healthcheck (maybe add to testing layer)
- [ ] Regenerate all architecture images
- [x] Decouple alpine upstream image in `Containerfile`, `docker-compose.yml`, and `drone.yml`

**Comment by gautada** [comment]
Not doing this anymore.
